### ISSUE TITLE
bootstrap zoomable css

### ISSUE THREAD

**Issue by xuanngo2001** [xuanngo2001/cust-live-deb#367]
https://bootsnipp.com/snippets/K0e9x

**Comment by xuanngo2001** [comment]
```
header /* delet it */
{
    height:100vh;
    background-color:#444444;
    font-family:roboto;
}

#demo h1 /* delet it */
{
    text-align:center;
    color:#888;
    padding-bottom:5px;
}

#demo p /* delet it */
{
    text-align:center;
    color:#777;
    padding-bottom:15px;
    font-size:21px;
    letter-spacing:1px;
}

#demo .row /* delet it */
{
    padding-top:20vh;
    padding-bottom:40px;
}

#demo img
{
    box-shadow:1px 1px 5px #000;
    max-height:15em; /* delet it */
}

#demo img:hover
{
    transition:all 0.6s; /* Change Speed */
    -ms-transform: scale(2, 2); /* IE 9 */
    -webkit-transform: scale(2, 2); /* Safari */
    transform: scale(2, 2); /* Change Size */
    overflow:visible;
    z-index:1 !important; /* you can change it, but better let this in default */
}


#demo .item-1:hover
{
    -ms-transform: translate(100px); /* IE 9 */
    -webkit-transform: translate(100px); /* Safari */
    transform: translate(100px); /* Change Offset */
    z-index:2; /* you can change it, but better let this in default */
}

#demo .item-2:hover
{
    z-index:2; /* you can change it, but better let this in default */
}

#demo .item-3:hover
{
    -ms-transform: translate(-100); /* IE 9 */
    -webkit-transform: translate(-100px); /* Safari */
    transform: translate(-100px); /* Change Offset */
    z-index:2; /* you can change it, but better let this in default */
}
```

**Comment by xuanngo2001** [comment]
https://www.codeply.com/go/JuADMG3eTG/bootstrap-image-hover-css-zoom-scale

```html
<div class="container">
<hr>
  <div class="row">
  
    <div class="col-md-4 img-hover">
    
      <img class="img-responsive img-rounded" src="http://placehold.it/300">
    
    </div>
  
  </div>
  
</div>
```

```css
.img-hover img {
    -webkit-transition: all .3s ease; /* Safari and Chrome */
  	-moz-transition: all .3s ease; /* Firefox */
  	-o-transition: all .3s ease; /* IE 9 */
  	-ms-transition: all .3s ease; /* Opera */
  	transition: all .3s ease;
  	position:relative;
}
.img-hover img:hover {
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-transform:translateZ(0) scale(1.20); /* Safari and Chrome */
    -moz-transform:scale(1.20); /* Firefox */
    -ms-transform:scale(1.20); /* IE 9 */
    -o-transform:translatZ(0) scale(1.20); /* Opera */
    transform:translatZ(0) scale(1.20);
}
  
.img-hover:hover:after {
    content:"";
    position:absolute;
    top:0;
    left:0;
    z-index:2;
    width:30px;
    height:30px;
    border:1px solid #000;
}
  
.grayscale {
  -webkit-filter: brightness(1.10) grayscale(100%) contrast(90%);
  -moz-filter: brightness(1.10) grayscale(100%) contrast(90%);
  filter: brightness(1.10) grayscale(100%); 
}
```
